Add a missing header that caused compile to fail
http://rubyforge.org/tracker/index.php?func=detail&aid=29073&group_id=1924&atid=7497

package.c: In function ‘package_clear_cache’:
package.c:21: error: implicit declaration of function ‘st_free_table’
package.c: In function ‘package_use_cache’:
package.c:29: error: implicit declaration of function ‘st_init_numtable’
package.c:29: error: cast to pointer from integer of different size
package.c: In function ‘package_free’:
package.c:46: error: implicit declaration of function ‘st_delete’
package.c: In function ‘package_new_from_header’:
package.c:72: error: implicit declaration of function ‘st_lookup’
package.c:79: error: implicit declaration of function ‘st_insert’
(cherry picked from commit e4514fe960f6a802c21a6e13abf213c53d147802)